version: '3.9'
services:
  db:
    image: postgres:latest
    container_name: fastapi_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_NAME} -h localhost -p 5432" ]
      interval: 2s
      timeout: 2s
      retries: 10
  app:
    build:
      context: .              # Path to your Dockerfile (usually project root)
      dockerfile: Dockerfile  # Optional if the file is named 'Dockerfile'
    ports:
      - "8000:8000"
    container_name: fastapi-app
    depends_on:
      db:
        condition: service_healthy #the app will wait till the database is ready to use before starting
