# Test your FastAPI endpoints
@HOST=http://localhost:8000

###Get all products
GET {{HOST}}/products

###Create new product
POST {{HOST}}/products
Content-Type: application/json

{
  "name": "Example Product",
  "price": 19.99
}

###Get a specific product
@product_id=1
GET {{HOST}}/products/{{product_id}}
